model:
  embed_dim: 3
  lossconfig:
    disc_start: 50001
    kl_weight: 0.000001
    disc_weight: 0.5
    disc_in_channels: 1
  ddconfig:
    double_z: True
    z_channels: 3
    resolution: [128, 128]
    in_channels: 1
    out_ch: 1
    ch: 128
    ch_mult: [1, 2, 4]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
  ckpt_path: ./results/dynamic_radio_vae/model-17-raw-model-only.pt

data:
  name: dynamic_radio_single_frame_vae
  data_root: /data/fzj/CARLA_0.9.15/datasets/DynamicRadioMap/MultiScene20_RF300M8Runs_RadioMapSeerPack
  split_file: split_mixed_50_50.json
  split: train
  val_split: val
  source: png
  frame_stride: 1
  cache_size: 8
  batch_size: 20

trainer:
  gradient_accumulate_every: 2
  lr: !!float 5e-6
  min_lr: !!float 5e-7
  train_num_steps: 150000
  save_and_sample_every: 5000
  rolling_save_every: 1000
  rolling_keep: 10
  auto_resume: False
  initial_step: 85000
  val_every: 5000
  val_num_batches: 100
  log_freq: 100
  results_folder: ./results/dynamic_radio_vae_mixed_50_50
  amp: False
  fp16: False
